In [1]:
import numpy as np
import pandas as pd
from pandas import array

12.1. Нэг хэмжээст хоёр массивыг нийлүүлж, элементүүдийн тоог хэвлэ.

In [2]:
massive_1 = np.array([1, 2, 3, 4, 5])

massive_2 = np.array([6, 7, 8, 9, 10])

massive_1 = np.concatenate((massive_1, massive_2))

print(massive_1)

[ 1  2  3  4  5  6  7  8  9 10]


12.2. Нэг хэмжээст массивыг хуулж, хуулсан массивын элементүүдийг эрэмбэл.

In [3]:
massive_1 = np.array([1, 2,7, 8, 15, 9, 13, 3, 4, 5])

massive_2 = np.copy(massive_1)

massive_2.sort()

print(massive_1)
print(massive_2)

[ 1  2  7  8 15  9 13  3  4  5]
[ 1  2  3  4  5  7  8  9 13 15]


12.3. Хоёр хэмжээст массивын элементүүдийн нийлбэрийг ол.

In [4]:
massive_1 = np.array([1, 2,7, 8, 15, 9, 13, 3, 4, 5])

print(np.sum(massive_1))

67


12.4. Хоёр хэмжээст массивын элементүүдийг эрэмбэлж, сондгой индекстэй элементүүдийн үржвэрийг ол.

In [5]:
massive_1 = np.array([[1, 2, 7, 8, 15], [9, 13, 3, 4, 5]])

for i in range(1, massive_1.ndim, 2):
    for j in range(1, len(massive_1[0]), 2):
        print(massive_1[i][j])

13
4


12.5. Хоёр хэмжээст массивын тэгш индекстэй элементүүдийг хуулбарлаж, хамгийн их хуваагчийг ол.

In [6]:
massive_1 = np.array([[1, 2, 7, 8, 15], [9, 13, 3, 4, 5]])

massive_2 = []

for i in range(0, massive_1.ndim, 2):
    for j in range(0, len(massive_1[0]), 2):
        massive_2.append(massive_1[i][j])

massive_2 = array(massive_2)

for i in range(int(max(massive_2)/2), 0, -1):
    hieh = False
    for item in massive_2:
        if item % i == 0:
            hieh = True
            continue
        hieh = False
        break
    if hieh:
        print(i)
        break

1


12.6. 5 хичээлийн код, нэр бүхий цувааг үүсгэж, 3 дахь хичээлийн нэрийг солж, цувааг хэвлэ.

In [7]:
lessons = np.array([{"code1"    :   "name1"},
                    {"code2"    :   "name2"},
                    {"code3"    :   "name3"},
                    {"code4"    :   "name4"},
                    {"code5"    :   "name5"},
                ])

lessons[0]["code3"]="changed_name"
print(lessons)

[{'code1': 'name1', 'code3': 'changed_name'} {'code2': 'name2'}
 {'code3': 'name3'} {'code4': 'name4'} {'code5': 'name5'}]


12.7. csv файл татаж авах холбоос: https://www.w3schools.com/python/pandas/dirtydata.csv.txt алдаатай хоосон нүдтэй мөрийг алгасаж хэвлэ.

In [8]:
df = pd.read_csv("./assets/dirtydata.csv")

df.dropna(inplace=True)
df['Date'] = pd.to_datetime(df['Date'])
df.dropna(subset=['Date'], inplace = True)
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)

print(df)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97 

12.8. Дараах csv файл татан авч https://www.w3schools.com/python/pandas/dirtydata.csv.txt   “Pulse” баганийн 100-с 110 хооронд орших өгөгдлүүдийг хэвлэ.

In [9]:
df = pd.read_csv("./assets/dirtydata.csv")

print(df.loc[df["Pulse"]>100].loc[df["Pulse"]<110]["Pulse"])

2     103
3     109
5     102
7     104
8     109
10    103
13    106
14    104
19    103
21    108
24    105
25    102
28    103
30    102
Name: Pulse, dtype: int64
